slice_name: Growth Rate
viz_type: line
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - country_name
  limit: '25'
  markup_type: markdown
  metrics:
  - sum__SP_POP_TOTL
  num_period_compare: '10'
  row_limit: 5000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  time_range_endpoints:
  - inclusive
  - exclusive
  until: '2014-01-02'
  viz_type: line
query_context: null
cache_timeout: null
uuid: 7126aed3-c70b-4f5c-a0c7-5aea4b32607c
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
