slice_name: Scatterplot
viz_type: deck_scatter
params:
  color_picker:
    a: 0.82
    b: 3
    g: 0
    r: 205
  datasource: 5__table
  granularity_sqla: null
  groupby: []
  mapbox_style: mapbox://styles/mapbox/light-v9
  max_radius: 250
  min_radius: 1
  multiplier: 10
  point_radius_fixed:
    type: metric
    value: count
  point_unit: square_m
  row_limit: 5000
  size: count
  spatial:
    latCol: LAT
    lonCol: LON
    type: latlong
  time_grain_sqla: null
  time_range: ' : '
  time_range_endpoints:
  - inclusive
  - exclusive
  viewport:
    bearing: -4.952916738791771
    latitude: 37.78926922909199
    longitude: -122.42613341901688
    pitch: 4.750411100577438
    zoom: 12.729132798697304
  viz_type: deck_scatter
query_context: null
cache_timeout: null
uuid: 68e72304-7fba-4adb-8696-c4fe99d5db4a
version: 1.0.0
dataset_uuid: c4ae2fd1-21b5-46d7-b572-337cf84bc785
