slice_name: Treemap
viz_type: treemap_v2
params:
  compare_lag: '10'
  compare_suffix: o10Y
  country_fieldtype: cca3
  entity: country_code
  granularity_sqla: year
  groupby:
  - region
  - country_code
  limit: '25'
  markup_type: markdown
  metric: sum__SP_POP_TOTL
  row_limit: 5000
  show_bubbles: true
  since: '1960-01-01'
  time_range: '2014-01-01 : 2014-01-02'
  time_range_endpoints:
  - inclusive
  - exclusive
  until: now
  viz_type: treemap_v2
query_context: null
cache_timeout: null
uuid: f5858a60-39df-4260-a42e-0704beac0471
version: 1.0.0
dataset_uuid: a29e44bc-dd2e-41dd-9ba9-b97af441d168
